### ISSUE TITLE
Online Manual broken (readthedocs)

### ISSUE THREAD

**Issue by drewrisinger** [pyGSTio/pyGSTi#170]
**Describe the bug**
No documentation is available on the ReadTheDocs manual page:  https://pygsti.readthedocs.io/en/latest/

**To Reproduce**
1. Go to https://pygsti.readthedocs.io/en/latest/
2. Click any link
3. Link either doesn't go anywhere (no effect) or links to a page saying the desired page doesn't exist.

**Environment (please complete the following information):**
   - Chrome web browser

**Comment by sserita** [comment]
You are right, the "latest" ReadTheDocs are broken (corresponding to the `master` branch) but the docs for the `beta` or `develop` branches do work, so this will be resolved with the next official release.

**Comment by enielse** [comment]
After fixing multiple failure points:
- the sphinx autosummary didn't recurse properly, and needed a new template (#206)
- readthedocs build times were in excess of 900s, causing the builds to fail because they timed out.  This has been, at least for now, fixed by moving from autosummary to the newer and faster autoapi sphinx extension (294fe445e667be09e744da38fccde8919a622edc)

Now the docs are built and [available](https://pygsti.readthedocs.io/en/latest/) for version 0.9.10 (latest, stable, and beta builds are all passing).

**Comment by drewrisinger** [comment]
Great, thank you!
