### ISSUE TITLE
Report generation hangs on missing latex packages

### ISSUE THREAD

**Issue by oliverdial** [pyGSTio/pyGSTi#2]
Report generation hangs on systems where latex packages (etoolbox) in my case are missing.  It'd be nice if we aborted with an error in this case, or at least let the user see the output from latex so it's evident what's happening.

**Comment by enielse** [comment]
Thanks for reporting this.  I've confirmed this issue and have added it to the list of "non-critical bugs" that we plan to fix by the next release.  I'm thinking this is non-critical in that once the latex packages are installed it's not a problem anymore.  Please let us know if this isn't the case and this is a more urgent issue, and we can work up a fix quickly.

Let's leave this issue open until it's actually fixed.  I'll comment again once that happens.

**Comment by enielse** [comment]
In the just-released **version 0.9.1 of pyGSTi**, we've made an effort to keep pdflatex from hanging (waiting for user input) when a needed package is missing, **fixing this issue in almost all cases**.

PyGSTi now calls pdflatex (using subprocess) and passes it the flags -interaction=nonstopmode and -halt-on-error to keep it from stalling.  Additionally, if /dev/null exists, stdin is redirected to /dev/null to further dissuade pdflatex from waiting for input.  If pdflatex aborts with a failure code, pyGSTi will raise a CalledProcessError after dumping the captured standard error to the user's stdout.  My expectation is that this addresses *most* of the issues with pdflatex missing packages, but that there could be a few cases where pdflatex still hangs (despite all our coaxing to get it to just abort!).  Windows systems seem more at risk since they don't have a /dev/null.

**I'm marking this issue as closed, since most problem cases should be addressed now.**
