### ISSUE TITLE
Creating a gate set from scratch dimension

### ISSUE THREAD

**Issue by bpwilliams** [pyGSTio/pyGSTi#21]
In Tutorial 01 Section Creating a GateSet from scratch how do you set the dimension? When I write the file "MyTargetGateset.txt" the basis is ``UNKNOWN".

**Comment by enielse** [comment]
Hello, and thanks for alerting me to this lacking the Tutorial's explanation.  The short answer, is that you want to add a line which sets the basis, like

`gateset1.set_basis("pp",2)`

before calling `pygsti.io.write_gateset(...)` to save the `GateSet` to a text file.   Specifying a the above means that the 4x4 gate matrices should be thought of as being in the "Pauli product" ("pp") basis of dimension "2", i.e. the 4 Pauli matrices I, X, Y, and Z.

When using `pygsti.construction.build_gateset`, the basis is automatically set, and defaults to the Gell-Mann ("gm") type since these matrices can be constructed for any Hilbert space dimension.  You can specify a different basis by setting the optional `basis` argument.  For example

`gateset3 = pc.build_gateset( [2], [('Q0',)], ..., basis='pp') ` 

Hopefully this answers your question. I'll plan to add some explanation about bases to Tutorial 01 as well.

**Comment by enielse** [comment]
Just to follow up a year later - the recently released pyGSTi version 0.9.4 includes a tutorial on bases, and is also more robust at setting the basis of `GateSet` objects then they're created.  It's worth mentioning however, that as of pyGSTi 0.9.4 to set the basis of a `GateSet` you've created from scratch, you do:
```
gateset1.basis = pygsti.obj.Basis("pp",2)
```
instead of using the `set_basis` method I described above which is now deprecated.  Giving `basis='pp'` as an argument to `build_gateset` still works as before (though the Pauli-product `'pp'` basis is now the default so you don't actually *need* to specify it).
