### ISSUE TITLE
Memory leakage in cythonized 'mapforwardsim_calc' 

### ISSUE THREAD

**Issue by SchineCompton** [pyGSTio/pyGSTi#226]
**Describe the bug**

Memory leakage in cythonized `mapforwardsim_calc`. There is memory leakage when calculating the Jacobbian in `custom_leastsq` function. I have fed it with 300GB memory and it still gets killed. The size of the returned Jacobbian matrix is not very large.

**To Reproduce**
Steps to reproduce the behaviour:
1. Get some noisy data that requires a larger iteration number to converge.
2. Observe pygsti eats all your memory and get killed, regardless of the mem limit settings.

**Expected behaviour**
Produce results within the mem limit settings.

**Environment:**
 - pyGSTi version [v0.9.10] with windows hot-fix #223 
 - python version: 
        Python 3.8.12 [MSC v.1916 64 bit (AMD64)]
        Python 3.9.7 [GCC 7.5.0] :: Anaconda, Inc. on linux
 - OS 
        Windows 10 Enterprised 20H2
        CentOS Linux release 8.5.2111,  4.18.0-305.10.2.el8_4.x86_64

**Additional context**

- I tried to fall back to the `mapforwardsim_calc_generic` model, it doesn't seem to be helpful. 
- This happens only when running GST in CPTP mode. TP seems not affected.  
- I also tried to revert the windows hot fix and run the code on a Linux machine, not helpful.

**Comment by coreyostrove** [comment]
Hi @SchineCompton,

Thank you for reporting this issue. We're looking into this behind the scenes, but if you could provide some additional context that would be helpful for us pinpointing the bug. Could you attach a minimal script or jupyter notebook with code that reproduces this error?

-Corey

**Comment by SchineCompton** [comment]
Dear Corey,

Thanks very much for your reply.

We used one of our customized qutrit models, which is defined here [qutrit_model.py](https://gist.github.com/SchineCompton/7a02cd8d9187ca3e3af0d1ecbeb0fffb#file-qutrit_model-py). 

You can reproduce this bug by running [run_gst.py](https://gist.github.com/SchineCompton/7a02cd8d9187ca3e3af0d1ecbeb0fffb#file-run_gst-py) with the following dataset we provide [GSTData.zip](https://github.com/pyGSTio/pyGSTi/files/8003706/GSTData.zip).

**Comment by SchineCompton** [comment]
I have some updates. It seems only the models in the "legacy" folder would not release the memory; I tried to use the models that were not in that folder and the memory get released properly.

**Comment by coreyostrove** [comment]
Hi @SchineCompton,

Thanks for sharing the code and data samples. I wasn't able to reproduce the _exact_ buggy behavior you were seeing, but I did indeed run into some issues when trying to run GST on your qutrit model using the map forward simulator. I was however able to get things working by switching your model to the matrix forward simulator option and I'd suggest that as a workaround in the meantime while we look more into why the map forward simulator isn't working. (Note that the choice of forward simulator, while having practical implications on the backend, shouldn't result in any difference in the final GST results).

You can switch the forward simulator by either adding the one-liner `qutritMDL.sim="matrix"` to your function `create_qutrit_model` in qutrit_model.py or adding `target_model.sim="matrix"`  before the function call to run GST in run_gst.py. Let us know if this works for you.

-Corey

**Comment by SchineCompton** [comment]
Thanks for the reply. We'll try the matrix forward simulator. Many thanks again for all the help!

**Comment by coreyostrove** [comment]
Hi @SchineCompton,

The implementations of the forward simulators isn't something I had a hand in myself, so I'll defer to @enielse and @sserita who've worked directly on their implementations if they want to add any clarifications or extra details
 
That said, at their core both forward simulators are performing standard "Schrodinger" style forward simulations. That is, they propagate the state of the system forward in time through a circuit by doing matrix-vector multiplication of the vectorized density matrix of the system (written in the appropriate basis) with the transfer matrix representation of the gates.

The difference is in how "smart" the simulators are in how they approach this. In the map forward simulator the simulation proceeds exactly as I described starting from some initial state and doing a sequence of matrix-vector multiplications. The matrix forward simulator instead takes the circuits and does a series of matrix-matrix multiplications to get the effective transfer matrix for the circuit, caching relevant intermediate results along the way. Matrix-matrix multiplication is more expensive than matrix-vector multiplication, but by doing it this way we can take advantage of the cached results to avoid duplicating work. GST experiments have a very particular/repetitive structure in which we take various "germ" circuits and raise them to various powers and then for each of these powers sandwich them between various combinations of state prep and measurement fiducials in a kind of "plaquette" structure. You can imagine why given this experiment design it's useful to construct this cache.

That said, it's not universally better to do it the way the matrix forward simulator does. For starters, pygsti (despite the name) isn't limited to fitting/simulating GST experiments. For example, there is pretty comprehensive functionality for working with randomized benchmarking experiments (on many qubits) in which, by design, our experiment designs lack a lot of repeating structure. In this context doing the matrix-matrix multiplication and building up a cache is a clear net loss. More subtly, it's also not universally better even for GST-like experiment designs once you start scaling up past a single qubit (it can be, but it depends on a lot more details and your computational platform). Some complications include: the memory costs for storing the cache are expensive, matrix-matrix multiplication scales like O(N^3) while matrix-vector multiplication scales like O(N^2) which means if you don't have a sufficiently large number of repeated calculations you can have a net loss, caching is less amenable to parallelization across many processors since processor-processor communication is expensive. That's not a comprehensive list, but does cover some of the main issues. 

The rule of thumb we've found empirically is that for 2-qubit and larger systems with some amount of parallelization the map simulator is typically faster, so that is the default for those systems. Your one-qutrit system is in an intermediate regime where I'd expect both to have comparable performance

-Corey

**Comment by SchineCompton** [comment]
Thanks so much for the detailed reply!

**Comment by enielse** [comment]
A quick update on this:  I attempted to reproduce the behavior using the files linked to above.  I ran `run_gst.py` on my OS X laptop (16 GB RAM) and the script completed and while consuming at most 0.6% of my available memory.  I didn't observe this memory leak, but it's possible this is a Windows-specific problem.  I and the other pygsti developers will continue to try to locate this issue and will post updates on this thread.  If others encounter memory leaks please continue to send us examples.

**Comment by sserita** [comment]
@SchineCompton We have not been able to reproduce this specific behavior in a while, and the code base has changed significantly since the original reporting.

Can I ask you to check whether this is still an issue for you with the most up-to-date code, either 0.9.10.1 or the tip of develop? If so, we'll continue to dig into this, but if not, I'm considering closing this stale issue.

**Comment by SchineCompton** [comment]
@sserita Thanks for the comments. We have moved on to the new version without any problems. Many thanks.
