### ISSUE TITLE
Bug with pygsti.circuits.Circuit.append_circuit()

### ISSUE THREAD

**Issue by giangiac** [pyGSTio/pyGSTi#264]
Method `pygsti.circuits.Circuit.append_circuit()` should return a `Circuit`, but `None` is returned.

There is a missing "return" statement in:
https://github.com/pyGSTio/pyGSTi/blob/master/pygsti/circuits/circuit.py#L2137

I would fix it myself, but wanted to check the expected behavior.
In fact, `append_circuit()` uses `insert_circuit()` and its implementation seems strange since it returns a circuit that is not editable anymore:
https://github.com/pyGSTio/pyGSTi/blob/master/pygsti/circuits/circuit.py#L2083
Is this what is expected?

**Comment by sserita** [comment]
Hi, thanks for your bug report! This is now fixed in a bugfix branch and will be part of the next release. A few words about the intended usage: Functions like `append_circuit()` were designed to act on immutable circuits, aka they do a copy, edit the circuit, and then return another immutable circuit. Meanwhile, functions like `append_circuit_inplace()` were designed to act on mutable circuits and do no copy.

The new behavior (in addition to the return fixes) is that the non-inplace versions now return a circuit that has the same mutability as the original circuit. However, note that if performance is desired, it is still better to modify the circuit inplace.

**Comment by sserita** [comment]
Closed as this is now in 0.9.11 release
