### ISSUE TITLE
TypeError: do_long_sequence_gst() got an unexpected keyword argument 'gaugeOptRatio'

### ISSUE THREAD

**Issue by omarshehab** [pyGSTio/pyGSTi#33]
I am getting the following error while trying the example from [Getting started quickly with Gate Set Tomography](http://www.pygsti.info/tutorials/00_Quick_and_easy_GST.html). I would appreciate if anyone could look into the issue. Thanks.

> Traceback (most recent call last):
>   File "gst.py", line 62, in <module>
>     gaugeOptRatio=1e-3, constrainToTP=True)
> TypeError: do_long_sequence_gst() got an unexpected keyword argument 'gaugeOptRatio'
>

**Comment by omarshehab** [comment]
PS. I was able to execute the code after removing 

> gaugeOptRatio=1e-3, constrainToTP=True

. I would like to know the explanation if anyone experienced knows.

**Comment by kmrudin** [comment]
Thanks for the catch!  The tutorials on pygsti.info are deprecated now; we should probably update the website to reflect that.  If you use the tutorials hosted on github (pyGSTi/jupyter_notebooks/Tutorials/), they should be up-to-date with the code base.  Sorry for the inconvenience!

**Comment by omarshehab** [comment]
Thanks Kenny!

**Comment by enielse** [comment]
Just a quick followup to close this out.  With the recent release of pyGSTi 0.9.4 the "www.pygsti.info" web page has been updated to link to the current versions of the tutorial notebooks on github.  I think originally we didn't do this because back then github would display .ipynb files as raw JSON instead of rendering it nicely as it does now.  So this issue should be permanently resolved now.
