### ISSUE TITLE
A problem about matrix

### ISSUE THREAD

**Issue by Jack-www** [pyGSTio/pyGSTi#330]
Sorry but I'm curious about the reason why setting the matrix forms of the I,X,Y,Z gates to be all identity matrices in file "symplectic.py". Will they be changed later？

complete_s_dict = {}
complete_p_dict = {}

# The Pauli gates
complete_s_dict['I'] = _np.array([[1, 0], [0, 1]], _np.int64)
complete_s_dict['X'] = _np.array([[1, 0], [0, 1]], _np.int64)
complete_s_dict['Y'] = _np.array([[1, 0], [0, 1]], _np.int64)
complete_s_dict['Z'] = _np.array([[1, 0], [0, 1]], _np.int64)

complete_p_dict['I'] = _np.array([0, 0], _np.int64)
complete_p_dict['X'] = _np.array([0, 2], _np.int64)
complete_p_dict['Y'] = _np.array([2, 2], _np.int64)
complete_p_dict['Z'] = _np.array([2, 0], _np.int64)

**Comment by sserita** [comment]
These are the symplectic matrix and phase vectors for the Pauli operations. It turns out that the symplectic matrices for the Paulis are actually the identity, with the phase vector (the `complete_p_dict`) being the thing that differentiates them in this representation.
So no, this is not changed later and is actually not a bug. Hope that helps!
