### ISSUE TITLE
Problems creating GST pdf report

### ISSUE THREAD

**Issue by maximilianruf** [pyGSTio/pyGSTi#34]
When creating a brief pdf report using pygsti, using a default directory name with underscores creates a LaTex error. This is caused by a failing math interpretation of the directory name in the \hypersetup{pdfinfo={ \putfield{pdfinfo}{}  }} section in the GST report template. Using \detokenize{directory_name} in the generated .tex file saves the problem, however this is not practical since this error is created every time when creating a new report. For now, my workaround is to pop the key 'defaultDirectory' before calling the function _to_pdfinfo in pygsti's results.py. When using several computers, this becomes cumbersome.

**Comment by enielse** [comment]
Thanks for pointing this out.  I believe this may be a Windows-only issue(?).  In any case, the recently released **pyGSTi v 0.9.4** addresses this issue in two ways:
1. Reports are now by default in HTML format rather than PDF, so there's no pdfinfo metadata to be an issue.  Note that the report-generation function in v0.9.4 is `pygsti.report.create_standard_report(...)` and that report generation has changed slightly so you may want to checkout the [report generation tutorial](https://github.com/pyGSTio/pyGSTi/blob/master/jupyter_notebooks/Tutorials/12%20Report%20Generation.ipynb).
2. If you still want a PDF report, you can just give a ".pdf" output name to `create_standard_report`.  In this case, we've now removed a bunch of the unnecessary metadata from the PDF including the "default directory", so you shouldn't have any LaTeX problems compiling it.

I'll mark this thread as closed since the original issue has definitely been removed.  If you have any other problems with report generation please create a new issue or reopen this one as you see fit.
