### ISSUE TITLE
splicing colormaps + LinLogNorm

### ISSUE THREAD

**Issue by Travis-S** [pyGSTio/pyGSTi#4]
In working through how we can splice together colormaps using the `plotting.splice_cmaps()` function and the `plotting.LinLogNorm()` class (both being developed on the `colormap_fix` branch), I am running into problems with the resulting `cmap` object. In particular, we would like to use `splice_cmaps()` to join together two colormaps, where the splicing takes place at the normalization of the `trans` variable of the `LinLogNorm()` class.

Preliminary imports and basic declarations:
```python
import pygsti
import matplotlib.cm as cm

linlog_trans = 11
norm = pygsti.report.plotting.LinLogNorm(trans=linlog_trans)
```

Code which works
```python
cmap = pygsti.report.plotting.splice_cmaps([cm.Greys, cm.Reds_r],\
                                           splice_points=[.1])
cmap(1)

>> (0.98154556050020103, 0.98154556050020103, 0.98154556050020103, 1.0)
```

Code which throws an error

```python
cmap = pygsti.report.plotting.splice_cmaps([cm.Greys, cm.Reds_r],\
                                           splice_points=[norm(11)])

cmap(1)

>> ValueError                                Traceback (most recent call last)
<ipython-input-90-4078524cc28b> in <module>()
----> 1 cmap(1)

/Users/tlschol/anaconda/lib/python2.7/site-packages/matplotlib/colors.pyc in __call__(self, X, alpha, bytes)
    548         # See class docstring for arg/kwarg documentation.
    549         if not self._isinit:
--> 550             self._init()
    551         mask_bad = None
    552         if not cbook.iterable(X):

/Users/tlschol/anaconda/lib/python2.7/site-packages/matplotlib/colors.pyc in _init(self)
    730         self._lut = np.ones((self.N + 3, 4), np.float)
    731         self._lut[:-3, 0] = makeMappingArray(
--> 732             self.N, self._segmentdata['red'], self._gamma)
    733         self._lut[:-3, 1] = makeMappingArray(
    734             self.N, self._segmentdata['green'], self._gamma)

/Users/tlschol/anaconda/lib/python2.7/site-packages/matplotlib/colors.pyc in makeMappingArray(N, data, gamma)
    467     if x[0] != 0. or x[-1] != 1.0:
    468         raise ValueError(
--> 469             "data mapping points must start with x=0. and end with x=1")
    470     if np.sometrue(np.sort(x) - x):
    471         raise ValueError(

ValueError: data mapping points must start with x=0. and end with x=1
```

The only difference between these two calls is in the `splice_points` declaration, where we use `[.5]` and `[norm(11)]`. Curiously, `norm(11)` returns `nan`. Ideas as to what are going on would be welcome.

The behavior we are trying to achieve would set the splice point for the colormap at the normalization value of the transition point. That way, when the normalization goes from logarithmic to linear, the colormap will change as well.

**Comment by jarthurgross** [comment]
The error is being thrown because the way `norm` is being called in this example causes it to set its `vmin` and `vmax` to the same value (11). This causes it to return `NaN` since there are divisions by `vmax - vmin` when called on data, which is what the error is all about.

In `color_boxplot`, `norm` is called on a set of data rather than a single point, so unless the data are identical a different `vmin` and `vmax` are set and you don't get this error. In your example, you can also manually set `vmin` and `vmax` when you define `norm`

    linlog_trans = 11
    vmin = 0
    vmax = 20
    norm = pygsti.report.plotting.LinLogNorm(vmin=vmin, vmax=vmax, trans=linlog_trans)

and you won't experience any errors.

For our purposes, the defaults of `splice_cmap` are set up so you shouldn't have to mess with them. `LinLogNorm` is designed to linearly map all values below `trans` to the interval [0, 0.5], and logarithmically map all values above `trans` to the interval [0.5, 1]. This means that when you have `vmin` and `vmax` set sensibly, `norm(linlog_trans)` will always be 0.5. `splice_cmaps` is set to default to assigning the different `cmap`s to equal intervals, so when joining two `cmap`s the transition from one to the other will occur at 0.5, matching the behavior of `LinLogNorm`.

**Comment by Travis-S** [comment]
This makes sense, and for now, we should rely on this default behavior. In the future, if we mess around more with the colormaps, we may need to revisit this.

Closing the issue for now.
