### ISSUE TITLE
Diamond Norm for a Pauli Channel

### ISSUE THREAD

**Issue by dcmckayibm** [pyGSTio/pyGSTi#40]
If I create a Pauli channel I don't seem to be getting consistency between the equation for the diamond norm of a Pauli channel (e.g. https://arxiv.org/abs/1109.6887 eqn. 5.4) and the pygsti function. 

Ex. 
`import numpy as np`
`pr1 = np.array([0.2,0.3,0.2,0.3])`
`pr2 = np.array([0.5,0.4,0.05,0.05])`
The pauli channel diamond norm is:
`np.sum(np.abs(pr1-pr2))`
This gives 0.8

If I input this into pygsti
`import pygsti`
`pygsti.gatetools.diamonddist(np.diag(pr1),np.diag(pr2),maxBasis='pp'))`
I get 0.3

**Comment by enielse** [comment]
Good question - there are a couple things you need to do differently to compute the diamond norm you're after:
1. pyGSTi's `diamonddist` function operates on the "superoperator" or "Pauli Transfer Matrix" form of the gate, not the Choi form (in which a Pauli channel is diagonal) - so you need to convert your diagonal Choi matrices to the superoperator form using `jamiolkowski_iso`.
2. pyGSTi's Pauli basis matrices are normalized to 1.0 rather than *d* (the dimension of the Hilbert space, so 2 for a single qubit) as they are in https://arxiv.org/abs/1109.6887, so you need to convert between normalizations by multiplying by a factor of 2<sup>2</sup> = 4.  The exponent of 2 comes from the fact that each element of `pr1` or `pr2` is the coefficient of a term like *P<sub>i</sub> rho P<sub>i</sub>* in which there are 2 Paulis.

So the following will give you what you're after:
```
import numpy as np
pr1 = np.array([0.2,0.3,0.2,0.3]) # understood to be in basis of norm=2 Paulis
pr2 = np.array([0.5,0.4,0.05,0.05])

import pygsti
g1 = pygsti.tools.jamiolkowski_iso(4*np.diag(pr1), 'pp','pp')
g2 = pygsti.tools.jamiolkowski_iso(4*np.diag(pr2), 'pp','pp')
pygsti.gatetools.diamonddist(g1,g2,mxBasis='pp')
```
This gives the 0.8 you expect.

**Comment by dcmckayibm** [comment]
Thanks, figured it was some different normalization issue.
