### ISSUE TITLE
Error when adding  a process matrix to the noise model

### ISSUE THREAD

**Issue by newsma** [pyGSTio/pyGSTi#70]
Hi! I'm trying to build a noise model using ExplicitOpModel. I want to add 'XX' gate to the basis gates. 

```
model1 = pygsti.objects.ExplicitOpModel([0,1],'pp')

#Populate the Model object with states, effects, gates,
# all in the *normalized* Pauli basis: { I/sqrt(2), X/sqrt(2), Y/sqrt(2), Z/sqrt(2) }
# where I, X, Y, and Z are the standard Pauli matrices.
model1['rho0'] = np.kron([ 1/sqrt(2), 0, 0, 1/sqrt(2) ],[ 1/sqrt(2), 0, 0, 1/sqrt(2) ]) # density matrix [[1, 0], [0, 0]] in Pauli basis
model1['Mdefault'] = pygsti.objects.UnconstrainedPOVM(
    {'00': np.kron([ 1/sqrt(2), 0, 0, 1/sqrt(2) ],[ 1/sqrt(2), 0, 0, 1/sqrt(2) ]),   # projector onto [[1, 0], [0, 0]] in Pauli basis
     '01': np.kron([ 1/sqrt(2), 0, 0, -1/sqrt(2) ],[ 1/sqrt(2), 0, 0, 1/sqrt(2) ]),
    '10': np.kron([ 1/sqrt(2), 0, 0, 1/sqrt(2) ],[ 1/sqrt(2), 0, 0, -1/sqrt(2) ]) ,
     '11': np.kron([ 1/sqrt(2), 0, 0, -1/sqrt(2) ],[ 1/sqrt(2), 0, 0, -1/sqrt(2) ])
    }) # projector onto [[0, 0], [0, 1]] in Pauli basis

angle=np.pi/4
U1_xx= [[np.cos(angle),0,0,-np.sin(angle)*1j],
             [0,np.cos(angle),-np.sin(angle)*1j,0],
              [0,-np.sin(angle)*1j,np.cos(angle),0],
              [-np.sin(angle)*1j,0,0,np.cos(angle)]]
XX= np.kron(U1_xx,np.conjugate(U1_xx))

mdl['Gxx',0,1]=XX

```

I get an error back pointing to the XX gate. I'm not sure why pysgti thinks 'XX' is of evolution type 'statevec'. 

> Cannot add an object with evolution type 'statevec' to a model with one of 'densitymx'

Also, is it possible to add Molmer Sorensen to the basis set of gates so that it can be used for circuit simulations?

**Comment by enielse** [comment]
**Quick answer**: you need to insert the line
`XX = pygsti.tools.change_basis(XX, 'std', 'pp')`
before the final line of your example.

**Explanation**:
You're getting this error because you're assigning a complex numpy array (see the elements of `XX` in your code above) to a model operation.  Since pyGSTi uses Hermitian bases for density matrices, it assumes that if you're specifying a super-operator (a map from density matrices to density matrices) as a dense array then this array will be *real* because a density matrix expressed in a Hermitian basis is a real vector.  Since your array is complex, it interprets it as a unitary operator on (complex) state-vectors as opposed to density matrices - i.e. it has evolution type `"statevec"`.  But `model1` in your example has already been setup to represent quantum states as density matrices (evolution type `"densitymx"`), so it gives you the error you see.

To fix this, you need to convert `XX` into the Pauli basis - that is, write the action of `XX` as you have it as the action on a state represented as a length-16 *real* vector specifying the 2-qubit density matrix as a linear combination of the 16 2-qubit product-of-two-Pauli matrices.  To do this, you can use the `change_basis` function to move from the "standard" (`"std"`) matrix-unit, basis you've expressed `XX` in to the "Pauli-product" (`"pp"`) basis the your model expects - that's what the line:
`XX = pygsti.tools.change_basis(XX, 'std', 'pp')` does.

**Comment by newsma** [comment]
Thank you for the explanation! Makes sense to me and works now.
 
As for the second question: when I'm defining the processor specification that I'm trying to benchmark or run any simulation on, XX gate is not one of the standard set of gates. Just like I did for the model building, is it possible to input XX as a basis get for the processor?

As an example, my goal is to do something like this: 

```
#Specify the device to be benchmarked - in this case 2 qubits
nQubits = 2
qubit_labels = [0,1] 

Gxx = ...........

gate_names = ['Gx', 'Gy','Gxx'] 


availability = {'Gxx':[(0,1)]}
pspec = pygsti.obj.ProcessorSpec(nQubits, gate_names, availability=availability, 
                                 qubit_labels=qubit_labels)
```

**Comment by enielse** [comment]
You should be able to just supply the `nonstd_gate_unitaries` argument to the `ProcessorSpec` constructor, which as its name implies, should contain the *unitary* for your MS gate, not the super operator.  So, using the `U1_xx` variable from your original post, you can just write:

```
gate_names = ['Gx', 'Gy','Gxx'] 
availability = {'Gxx':[(0,1)]}
pspec = pygsti.obj.ProcessorSpec(nQubits, gate_names, availability=availability, 
                                 qubit_labels=qubit_labels,
                                 nonstd_gate_unitaries={'Gxx': U1_xx})
```

**Comment by newsma** [comment]
That's perfect! Thanks for all the help, Erik!
