### ISSUE TITLE
Error when generating report for 2 qubit model testing

### ISSUE THREAD

**Issue by newsma** [pyGSTio/pyGSTi#78]
I get an assertion error when I generate the standard report for 2 qubit model testing. It works fine for single qubit model testing. I'm not sure if it is a bug or if I am doing something wrong, so decided to open a regular issue. 

**To Reproduce**
I couldn't upload a Jupyter notebook file here, so here is a GitHub link to the code I'm running: [https://github.com/newsma/pygsti_work/blob/master/2QubitModelTesting.ipynb](https://github.com/newsma/pygsti_work/blob/master/2QubitModelTesting.ipynb)

**Expected behavior**
Generate the standard report. 

**Environment (please complete the following information):**
 - pyGSTi version 0.9.7
 - python version 3.7
 - OS macOS Mojave 10.14.5

**Comment by enielse** [comment]
**I was able to run your notebook successfully using pyGSTi version 0.9.8** (though it took a while to generate the report!).  I doubt using version 0.9.7 is your issue though - **I think this is a SciPy problem**.

The assert statement that is failing on you checks to make sure that when we call `scipy.linalg.sqrtm` function we indeed get back the square root of the matrix we passed in.  I've seen this routine fail on seemingly easy cases (full rank, well conditioned matrices), which is why we added the assert statement.  

I you can easily access the pyGSTi source you're running, you could add a `print(A)` statement before the `sqrtA = _hack_sqrtm(A)` on line 87 of the optools.py file to figure out what matrix in particular `sqrtm` is failing for, and then you could try to just debug your `sqrtm` function.  I tested your notebook using SciPy version 1.1.0 - if your version is older than that you could try upgrading SciPy first and hope for an easy fix.  

You could also try upgrading pyGSTi to 0.9.8, but I don't think the new version changes anything about the way we take matrix square roots.

**Comment by newsma** [comment]
I had to downgrade scipy to 1.1.0 and things work, it fails with scipy 1.2.1.
